glm_api_url = "https://open.bigmodel.cn/api/paas/v4/chat/completions"
rabbitmq_host = "43.145.37.75"
rabbitmq_user = "bixing"
rabbitmq_pass = "Bixing@202505"
queue_name = "user.events.queue"
api_base_url = "http://app.bixing.com.cn"
api_token = "1b6a1051a3c645ea9bcbde36435fceef"
csv_path = "V1generated_user_cards.csv"
pkl_path = "/root/autodl-tmp/Bixing_API/ai_search/V1_user_vec.pkl"
embed_path = "/root/autodl-tmp/Bixing_API/ai_search/V1faiss_embeddings.npy"
model_dir = "/root/autodl-fs"
