glm_api_url = "https://open.bigmodel.cn/api/paas/v4/chat/completions"
rabbitmq_host = "124.221.49.124"
rabbitmq_user = "bixing"
rabbitmq_pass = "bixing2025"
queue_name = "gpu.ai.server.events.queue"
api_base_url = "http://test-app.bixing.com.cn"
api_token = ""

model_dir = "/root/autodl-tmp/models"

[elasticsearch]
url = "http://124.221.49.124:9201"
user = "elastic"
password = "Bixing@202505"
user_profile_index = "user_profile"
